name: Snake on Push

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Snake
        uses: Platane/snk@master
        with:
          github_user_name: dsslleagion
